env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  no-console: "off",
  no-param-reassign: "off",
  jsx-a11y/label-has-associated-control: "off",
  jsx-a11y/no-autofocus: "off"
}
